sudo: required
services:
  - docker
before_install:
- docker pull sonatype/nexus3
- docker run -d --rm -p 127.0.0.1:8081:8081 --name nexus sonatype/nexus3
- cp -f tests/fixtures/dot-nexus-cli ~/.nexus-cli
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7-dev"
install:
  - pip install .[test]
script:
  - pytest -m 'not integration'
  - ./tests/wait-for-nexus.sh && pytest -m integration
